# IMPORT DATA


In [1]:
#library untuk membuat, mengubah dan mengecek data pada tabel
import pandas as pd
pd.set_option('display.max_colwidth', 20)
# pd.reset_option('^display.', silent=True)
# pd.set_option('display.max_rows', 3)
import numpy as np
#Membaca data csv
data_path = "C:\\Users\\HP\\Downloads\\TUGAS AKHIR\EXCEL KODINGAN\\DataProdukVers5.csv"
data_product = pd.read_csv(data_path)

#Menampilkan data
data_product.head(3)

No                 Nama       Jenis                 Merk  \
0   1  Marigold Deep-Cl...  Facial Wash               NPure   
1   2     Acne Facial Wash  Facial Wash  SCARLETT WHITENING   
2   3  Hy! Amino Wow-te...  Facial Wash          YOU BEAUTY   

           Jenis Kulit Permasalahan Kulit            Deskripsi  \
0  normal, berminya...      normal, kusam  Pembersih muka d...   
1  normal, berminya...      normal, kusam  Scarlett Whiteni...   
2       normal, kering      normal, kusam  Facial Wash yang...   

             Kandungan               Gambar  
0  Water, Glycerin,...  https://www.beau...  
1  Aqua, Lauryl Glu...  https://www.beau...  
2  Water, Sodium La...  https://www.beau...

# TEXT PREPROCESSING


In [2]:
pd.set_option('display.max_colwidth', 150)
#Drop kolom yang tidak dibutuhkan
data_product = data_product.drop(labels=["No","Merk","Deskripsi","Gambar"], axis='columns')

data_product.head(2)

Nama       Jenis   \
0  Marigold Deep-Cleanse Facial Wash  Facial Wash   
1                   Acne Facial Wash  Facial Wash   

                            Jenis Kulit Permasalahan Kulit  \
0  normal, berminyak, kering, kombinasi      normal, kusam   
1          normal, berminyak, kombinasi      normal, kusam   

                                                                                                                                               Kandungan  
0  Water, Glycerin, Coco-Betaine, Disodium Cocoamphodiacetate, Sodium Chloride, Potassium Cocoyl Glycinate, Calendula Officinalis Flower Extract, But...  
1  Aqua, Lauryl Glucoside, Acrylates Copolymer, Sodium Cocoyl Glyrcinate, Peg-40 Hydrogenated Castor Oil, Cocamidopropyl Betaine, Phenoxyethanol, Ami...

In [3]:
data_product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Nama                100 non-null    object
 1   Jenis               100 non-null    object
 2   Jenis Kulit         100 non-null    object
 3   Permasalahan Kulit  100 non-null    object
 4   Kandungan           100 non-null    object
dtypes: object(5)
memory usage: 4.0+ KB


In [4]:
data_textPre = pd.DataFrame()
data_textPre['data awal'] = data_product['Nama'] + " " + data_product['Jenis '] + " " + data_product['Jenis Kulit'] + " " + data_product['Permasalahan Kulit'] + " " + data_product['Kandungan']

In [5]:
data_textPre[['data awal']].head(3)

data awal
0  Marigold Deep-Cleanse Facial Wash Facial Wash normal, berminyak, kering, kombinasi normal, kusam Water, Glycerin, Coco-Betaine, Disodium Cocoampho...
1  Acne Facial Wash Facial Wash normal, berminyak, kombinasi normal, kusam Aqua, Lauryl Glucoside, Acrylates Copolymer, Sodium Cocoyl Glyrcinate, Peg...
2  Hy! Amino Wow-tery Hydrating Facial Wash Facial Wash normal, kering normal, kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium La...



## CASE FOLDING


In [6]:
data_caseFolding = pd.DataFrame(data=data_textPre['data awal'])
data_caseFolding.rename(columns={'data awal':'case folding'}, inplace=True)
# Case Folding
for i in range(0, len(data_caseFolding)):
  data_caseFolding['case folding'][i] = data_caseFolding['case folding'][i].lower()

In [7]:
data_caseFolding.head(3)

case folding
0  marigold deep-cleanse facial wash facial wash normal, berminyak, kering, kombinasi normal, kusam water, glycerin, coco-betaine, disodium cocoampho...
1  acne facial wash facial wash normal, berminyak, kombinasi normal, kusam aqua, lauryl glucoside, acrylates copolymer, sodium cocoyl glyrcinate, peg...
2  hy! amino wow-tery hydrating facial wash facial wash normal, kering normal, kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium la...

## TOKENIZING

In [8]:
pip install nltk

In [9]:
#Mengimport nltk
import nltk
# import reguler expression
import re
# import string
import string
#Mendownload package untuk menghapus tanda baca
nltk.download('punkt')
# impor word_tokenize dari modul nltk
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [10]:
#Tokenizing
data_tokenizing = pd.DataFrame(data=data_caseFolding['case folding'])
data_tokenizing.rename(columns={'case folding': 'tokenizing'}, inplace=True)

for i in range (0, len(data_tokenizing)):
  #Menghapus Angka
  data_tokenizing['tokenizing'][i] = re.sub(
      r"\d+", "", data_tokenizing['tokenizing'][i])
  #Menghapus Tanda Baca
  data_tokenizing['tokenizing'][i] = data_tokenizing['tokenizing'][i].translate(
      str.maketrans('', '', string.punctuation))
  #Menghapus Simbol (@)
  data_tokenizing['tokenizing'][i] = re.sub(
      r"@\S+", "", data_tokenizing['tokenizing'][i])
  #Menghapus URL
  data_tokenizing['tokenizing'][i] = re.sub(
      "http[s]?\://\S+", "", data_tokenizing['tokenizing'][i])
  #Menghapus tab atau line karakter
  data_tokenizing['tokenizing'][i] = re.sub(
      r"\n", "", data_tokenizing['tokenizing'][i])
  #Menghapus single alpabet
  data_tokenizing['tokenizing'][i] = re.sub(
      r"\b[a-zA-Z]\b", "", data_tokenizing['tokenizing'][i])
  #Menghapus berlebihan spasi
  data_tokenizing['tokenizing'][i] = re.sub(
      '\s+', ' ', data_tokenizing['tokenizing'][i])
  #Memisahkan kata menggunakan word_tokenize
  data_tokenizing['tokenizing'][i] = nltk.word_tokenize(
      data_tokenizing['tokenizing'][i])


In [11]:
data_tokenizing.head(3)

tokenizing
0  [marigold, deepcleanse, facial, wash, facial, wash, normal, berminyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, disodium, c...
1  [acne, facial, wash, facial, wash, normal, berminyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, gly...
2  [hy, amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betain...

## FILTERING

In [12]:
#Filtering
data_filtering = pd.DataFrame(data=data_tokenizing['tokenizing'])
data_filtering.rename(columns={'tokenizing': 'filtering'}, inplace=True)

#Mendownload package stopwords untuk menghapus kata kata yang tidak berarti dalam sebuah kalimat
nltk.download('stopwords')
from nltk.corpus import stopwords

#Stopword Bahasa Indonesia
indo_stopword = (stopwords.words('indonesian'))

#Stopword Bahasa Inggris
eng_stopword = (stopwords.words('english'))

#Data Stopword
data_stopword = indo_stopword
data_stopword.extend(eng_stopword)
data_stopword = str(data_stopword)

for i in range (0, len(data_filtering)):
  data_filtering['filtering'][i] = [word for word in data_filtering['filtering'][i] if not word in (data_stopword)]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [13]:
data_filtering.head(3)

filtering
0  [marigold, deepcleanse, facial, wash, facial, wash, normal, berminyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, disodium, c...
1  [acne, facial, wash, facial, wash, normal, berminyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, gly...
2  [amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, s...

## STEMMING

In [14]:
pip install PySastrawi

In [15]:
data_stemming = pd.DataFrame(data=data_filtering['filtering'])
data_stemming.rename(columns={'filtering': 'stemming'}, inplace=True)
#Stemming
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

#Membuat stemmer
Factory = StemmerFactory()
Stemmer = Factory.create_stemmer()

for i in range (0, len(data_stemming)):
  temp = []
  for j in range (0, len(data_stemming['stemming'][i])):
    data_stemming['stemming'][i][j] = Stemmer.stem(data_stemming['stemming'][i][j])
    temp.append(data_stemming['stemming'][i][j])
  data_stemming['stemming'][i] = temp

In [16]:
data_stemming.head(3)

stemming
0  [marigold, deepcleanse, facial, wash, facial, wash, normal, minyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, sodium, cocoam...
1  [acne, facial, wash, facial, wash, normal, minyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrci...
2  [amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, s...

## Menggabungkan hasil tahapam preprocessing

In [17]:
data_textPre_res = pd.concat([data_textPre, data_caseFolding, data_tokenizing, data_filtering, data_stemming], axis=1)

In [18]:
data_textPre_res.head(3)

data awal  \
0  Marigold Deep-Cleanse Facial Wash Facial Wash normal, berminyak, kering, kombinasi normal, kusam Water, Glycerin, Coco-Betaine, Disodium Cocoampho...   
1  Acne Facial Wash Facial Wash normal, berminyak, kombinasi normal, kusam Aqua, Lauryl Glucoside, Acrylates Copolymer, Sodium Cocoyl Glyrcinate, Peg...   
2  Hy! Amino Wow-tery Hydrating Facial Wash Facial Wash normal, kering normal, kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium La...   

                                                                                                                                            case folding  \
0  marigold deep-cleanse facial wash facial wash normal, berminyak, kering, kombinasi normal, kusam water, glycerin, coco-betaine, disodium cocoampho...   
1  acne facial wash facial wash normal, berminyak, kombinasi normal, kusam aqua, lauryl glucoside, acrylates copolymer, sodium cocoyl glyrcinate, peg...   
2  hy! amino wow-tery hydrating facial wash facial wash normal, kering normal, kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium la...   

                                                                                                                                              tokenizing  \
0  [marigold, deepcleanse, facial, wash, facial, wash, normal, berminyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, disodium, c...   
1  [acne, facial, wash, facial, wash, normal, berminyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, gly...   
2  [hy, amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betain...   

                                                                                                                                               filtering  \
0  [marigold, deepcleanse, facial, wash, facial, wash, normal, minyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, sodium, cocoam...   
1  [acne, facial, wash, facial, wash, normal, minyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrci...   
2  [amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, s...   

                                                                                                                                                stemming  
0  [marigold, deepcleanse, facial, wash, facial, wash, normal, minyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, sodium, cocoam...  
1  [acne, facial, wash, facial, wash, normal, minyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrci...  
2  [amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, s...

In [19]:
pd.set_option('display.max_colwidth', 60)
data_textPre_res.head(3)


data awal  \
0  Marigold Deep-Cleanse Facial Wash Facial Wash normal, be...   
1  Acne Facial Wash Facial Wash normal, berminyak, kombinas...   
2  Hy! Amino Wow-tery Hydrating Facial Wash Facial Wash nor...   

                                                  case folding  \
0  marigold deep-cleanse facial wash facial wash normal, be...   
1  acne facial wash facial wash normal, berminyak, kombinas...   
2  hy! amino wow-tery hydrating facial wash facial wash nor...   

                                                    tokenizing  \
0  [marigold, deepcleanse, facial, wash, facial, wash, norm...   
1  [acne, facial, wash, facial, wash, normal, berminyak, ko...   
2  [hy, amino, wowtery, hydrating, facial, wash, facial, wa...   

                                                     filtering  \
0  [marigold, deepcleanse, facial, wash, facial, wash, norm...   
1  [acne, facial, wash, facial, wash, normal, minyak, kombi...   
2  [amino, wowtery, hydrating, facial, wash, facial, wash, ...   

                                                      stemming  
0  [marigold, deepcleanse, facial, wash, facial, wash, norm...  
1  [acne, facial, wash, facial, wash, normal, minyak, kombi...  
2  [amino, wowtery, hydrating, facial, wash, facial, wash, ...

In [20]:
#Menjadikan dataset file xlsx
data_textPre_res.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/" +'Hasil Text Preprocessing.xlsx', index=False)

# Menggabungkan Kata

In [21]:
#Menggabungkan setiap kata dalam satu data
dataset_res = [] 

for i in range(0, len(data_textPre_res['stemming'])):
  temp = []
  temp = " ".join(data_textPre_res['stemming'][i])
  dataset_res.append(temp)

dataset = pd.DataFrame(dataset_res, columns=["data"])
dataset.head(3)

data
0  marigold deepcleanse facial wash facial wash normal miny...
1  acne facial wash facial wash normal minyak kombinasi nor...
2  amino wowtery hydrating facial wash facial wash normal k...

In [22]:
# Menjadikan dataset file xlsx
dataset.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/" +'Dataset Digabungkan.xlsx', index=False)

# PERHITUNGAN MANUAL

## MENGHITUNG KAMUS KATA MANUAL

In [23]:
# from nltk.tokenize import word_tokenize
# ##TFIDF MANUAL
# word_vocab=[]
# for i in range(0,len(dataset)):
#   words = dataset['data'][i].split()
#   for word in words:
#     if word not in word_vocab:
#       word_vocab.append(word)

# word_vocab = set(word_vocab)
# print('total data : ', len(data_textPre))
# print('total kata : ', len(word_vocab))

In [24]:
# word_vocab = sorted(set(word_vocab))
# print(word_vocab)

## PERHITUNGAN TF MANUAL

In [25]:
# n_data = len(dataset['data'])
# n_kata = len(word_vocab)

# data_tf = pd.DataFrame(np.zeros((n_data, n_kata)), columns=list(word_vocab))
 
# # Menghitung TF
# for i in range(n_data):
    
#     words = dataset['data'][i].split() # Words in the document
#     for w in words:
#         data_tf[w][i] = data_tf[w][i] + 1 / len(words) 
    
# data_tf   

In [26]:
# #Menjadikan dataset file xlsx
# data_tf.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/" +'hasilTFManual.xlsx', index=False)

## PERHITUNGAN IDF MANUAL

In [27]:
# idf = {}
 
# for w in word_vocab:
#     n = 0   
     
#     for i in range(n_data):
#         if w in dataset['data'][i].split():
#             n += 1
             
#     idf[w] =  (np.log((1+n_data)/(1+n)))+1

# print(idf)

In [28]:
# data_idf = pd.DataFrame.from_dict(idf, orient='index',columns=['Nilai IDF'])

In [29]:
# data_idf.head(3)

In [30]:
# #Menjadikan dataset file xlsx
# data_idf.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/" +'hasilIDFManual.xlsx', index=False)

## TFIDF MANUAL

In [31]:
# data_tf_idf = data_tf.copy()
 
# for w in word_vocab:
#     for i in range(n_data):
#         data_tf_idf[w][i] = data_tf[w][i] * idf[w]
         
# data_tf_idf

In [32]:
# #Melakukan normalisasi
# from sklearn import preprocessing
# import numpy as np

# normalizd_arr = preprocessing.normalize(data_tf_idf)

# after_normz = pd.DataFrame(normalizd_arr, columns=list(word_vocab) )
# after_normz

In [33]:
# #Menjadikan dataset file xlsx
# after_normz.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/" +'hasil_TFIDF_Manual.xlsx', index=False)

# 5 RECOMMENDATION

## IMPORT DATA PENGGUNA

In [34]:
data_path = "C:\\Users\\HP\\Downloads\\DataPengguna4.csv"
data_pengguna = pd.read_csv(data_path)
data_pengguna.head(3)

No Jenis Produk Jenis Kulit Permasalahan Kulit  \
0   1  Facial Wash      Normal             Normal   
1   2  Facial Wash      Normal              Kusam   
2   3  Facial Wash      Normal            Jerawat   

                                                     Kandungan  
0                                                          NaN  
1  Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, N...  
2  Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid...

In [35]:
data_pengguna = data_pengguna.drop(labels=["No"], axis='columns')
data_pengguna["Kandungan"].fillna(" ", inplace=True)
data_pengguna['input'] = data_pengguna['Jenis Produk'] + " " + data_pengguna['Jenis Kulit'] + \
    " " + data_pengguna['Permasalahan Kulit'] + \
    " " + data_pengguna['Kandungan']


In [36]:
data_pengguna["Kandungan"].fillna(" ", inplace=True)

## MEMBUAT DATA KEMUNGKINAN INPUTAN PENGGUNA

In [37]:
data_pengguna['input'] = data_pengguna['Jenis Produk'] + " " +  data_pengguna['Jenis Kulit'] + " " + data_pengguna['Permasalahan Kulit'] + " " + data_pengguna['Kandungan']

data_pengguna.head(3)

Jenis Produk Jenis Kulit Permasalahan Kulit  \
0  Facial Wash      Normal             Normal   
1  Facial Wash      Normal              Kusam   
2  Facial Wash      Normal            Jerawat   

                                                     Kandungan  \
0                                                                
1  Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, N...   
2  Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid...   

                                                         input  
0                                  Facial Wash Normal Normal    
1  Facial Wash Normal Kusam Hyaluronic Acid, Alpha Hydroxy ...  
2  Facial Wash Normal Jerawat Salicylic Acid, Sulfur, Azela...

## 5 REKOMENDASI BERDASARKAN DATA INPUTAN PENGGUNA

In [38]:
pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.


### JIKA INPUTAN PENGGUNA MASUK KE DALAM DATABASE

In [39]:
#TEXT PREPROCESSING INPUTAN
def text_pre_input_two (user_input):
  # CASE FOLDING
    user_input = user_input.lower()

  # TOKENIZING
    # Menghapus Angka
    user_input = re.sub(r"\d+", "", user_input)
    # Menghapus Tanda Baca
    user_input = user_input.translate(
        str.maketrans("", "", string.punctuation))
    # Menghapus Simbol (@)
    user_input = re.sub(r"@\S+", "", user_input)
    # Menghapus URL
    user_input = re.sub("http[s]?\://\S+", "", user_input)
    # Menghapus tab atau line karakter
    user_input = re.sub(r"\n", "", user_input)
    # Menghapus berlebihan spasi
    user_input = re.sub('\s+', ' ', user_input)
    # dilakukan proses tokenization pada user_input
    tokens_query = [str(tok) for tok in nltk.word_tokenize(user_input)]

  # FILTERING
    # Stopword Bahasa Indonesia
    indo_stopword = set(stopwords.words('indonesian'))

    # Stopword Bahasa Inggris
    eng_stopword = set(stopwords.words('english'))

    # Data Stopword
    data_stopword = str(indo_stopword) + " " + str(eng_stopword)

    # Data tanpa stopword
    tokens_query = [word for word in tokens_query if not word in data_stopword]

  # STEMMING
    the_query = []
    # Membuat stemmer
    Factory = StemmerFactory()
    Stemmer = Factory.create_stemmer()
    for i in range(0, len(tokens_query)):
        tokens_query[i] = Stemmer.stem(tokens_query[i])
        the_query.append(tokens_query[i])

    join_query = ' '.join(tokens_query)
    return (join_query)

In [40]:
print('Sebelum text preprocessing :')
print('Facial Wash Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid')
print('Setelah text preprocessing :')
a = 'Facial Wash Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid'
b = text_pre_input_two(a)
print(b)


Sebelum text preprocessing :
Facial Wash Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid
Setelah text preprocessing :
facial wash minyak normal dimethicone glycolic acid hyaluronic acid niacinamide retinol salicylic acid


In [41]:
#COSINE SIMILARITY AND GET THE RECOMMENDATION
from sklearn.metrics.pairwise import cosine_similarity

def get_recommendations_product_two(tfidf_dataset):

    # Mencari tingkat kemiripan antara user_input dengan dataset
    cos_sim = cosine_similarity(tfidf_dataset, tfidf_dataset)
    # print(cos_sim)
    df_cosim = pd.DataFrame(data=cos_sim)
    # display(df_cosim)

    #Mengambil nilai cosine similarity pada baris yang berisi inputan pengguna
    val_cos_sim = pd.DataFrame(data=cos_sim[-1,:], columns=['Cosine Similarity Score'])
    # display(val_cos_sim)

    # Mencari 5 teratas nilai kemiripan tertinggi
    top5 = val_cos_sim.sort_values("Cosine Similarity Score", ascending=False)[1:6]
    # display(top5)

    # Mencari index dari 5 nilai kemiripan teratas
    index = list(top5.index.values)

    return index, top5

In [42]:
pip install xlsxwriter

Note: you may need to restart the kernel to use updated packages.


In [43]:
#TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer

# import xlsxwriter module
import xlsxwriter

#contoh inputan pengguna
test_case = "Facial Wash Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid"

print(test_case)

# TFIDF vectorizer
vectorizer = TfidfVectorizer(analyzer='word', stop_words=list(data_stopword))
# melakuka text preprocessing pada inputan pengguna
user_input = text_pre_input_two(test_case)
# menambahkan ke dalam dataset
add_data = pd.DataFrame({'data':user_input}, index=[-1])
# print(add_data)

# membuat variabel baru untuk menampung data product
the_data = data_product

#percabangan agar produk yang direkomendasikan sesuai dengan kategori
if (test_case.find('Facial Wash')!=-1):
  print ('Facial Wash')
  th_idx = pd.concat([dataset[0:20],add_data]).reset_index(drop=True)
  the_product = the_data[0:20]
elif (test_case.find('Face Toner')!=-1):
  print ('Face Toner')
  th_idx = pd.concat([dataset[20:40],add_data]).reset_index(drop=True)
  the_product = the_data[20:40]
elif (test_case.find('Face Serum')!=-1):
  print('Face Serum')
  th_idx = pd.concat([dataset[40:60],add_data]).reset_index(drop=True)
  the_product = the_data[40:60]
elif (test_case.find('Moisturizer')!=-1):
  print('Moisturizer')
  th_idx = pd.concat([dataset[60:80],add_data]).reset_index(drop=True)
  the_product = the_data[60:80]
else :
  print('Sunscreen')
  th_idx = pd.concat([dataset[80:100],add_data]).reset_index(drop=True)
  the_product = the_data[80:100]
  

tfidf_dataset1 = vectorizer.fit_transform(th_idx['data'])
index, top5 = get_recommendations_product_two(tfidf_dataset1)

res_data = pd.DataFrame(the_product[['Nama', 'Jenis ']].iloc[index])
top5.index = res_data.index
fix_res = pd.concat([res_data, top5], axis=1)

display(fix_res)

df_tfidf_sklearn = pd.DataFrame(tfidf_dataset1.toarray(), columns=vectorizer.get_feature_names_out())
tfidf_tokens = vectorizer.get_feature_names_out()
df_tfidfvect = pd.DataFrame(data=tfidf_dataset1.toarray(
), index=th_idx.index.values, columns=tfidf_tokens)

display(df_tfidfvect)

# Menuliskan hasil ke excel
writer = pd.ExcelWriter('C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/HasilRekomendasiTrial.xlsx', engine='xlsxwriter')
row = 2
col = 0
fix_res.to_excel(writer, startrow=row)

work_book = writer.book
work_sheet =  writer.sheets["Sheet1"]
row-=2
work_sheet.write(row, col, test_case)
row+= 3

writer.close()

Facial Wash Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid
Facial Wash


Nama       Jenis   \
4   Hy! Amino Control Oil Control Facial Wash  Facial Wash   
3     Hy! Amino Ac-TtackAnti-Acne Facial Wash  Facial Wash   
5   Hy! Amino Glo-Win Brightening Facial Wash  Facial Wash   
0           Marigold Deep-Cleanse Facial Wash  Facial Wash   
17               Hydralife Mild Cleanser Foam  Facial Wash   

    Cosine Similarity Score  
4                  0.229273  
3                  0.203563  
5                  0.179483  
0                  0.172825  
17                 0.161652

acetate    acetyl  acetylated      acid      acne    acocia  acrylate  \
0   0.097310  0.122248    0.000000  0.247512  0.000000  0.000000  0.000000   
1   0.000000  0.000000    0.000000  0.094679  0.123548  0.140288  0.000000   
2   0.000000  0.000000    0.101618  0.187807  0.000000  0.000000  0.000000   
3   0.000000  0.000000    0.105752  0.244310  0.000000  0.000000  0.000000   
4   0.000000  0.000000    0.101216  0.280595  0.000000  0.000000  0.000000   
5   0.000000  0.000000    0.091159  0.210595  0.000000  0.000000  0.000000   
6   0.000000  0.000000    0.000000  0.255058  0.000000  0.000000  0.000000   
7   0.225340  0.000000    0.000000  0.047763  0.000000  0.000000  0.000000   
8   0.205605  0.000000    0.000000  0.130741  0.000000  0.000000  0.000000   
9   0.000000  0.000000    0.000000  0.080746  0.000000  0.000000  0.000000   
10  0.000000  0.000000    0.000000  0.000000  0.000000  0.000000  0.000000   
11  0.000000  0.000000    0.000000  0.000000  0.000000  0.000000  0.178966   
12  0.000000  0.000000    0.000000  0.031762  0.000000  0.000000  0.000000   
13  0.000000  0.000000    0.000000  0.058116  0.000000  0.000000  0.151672   
14  0.000000  0.000000    0.000000  0.000000  0.000000  0.000000  0.000000   
15  0.000000  0.000000    0.000000  0.153638  0.000000  0.000000  0.000000   
16  0.000000  0.000000    0.000000  0.075107  0.000000  0.000000  0.000000   
17  0.000000  0.000000    0.000000  0.083212  0.000000  0.000000  0.000000   
18  0.000000  0.000000    0.000000  0.093451  0.243889  0.000000  0.000000   
19  0.000000  0.000000    0.000000  0.145436  0.000000  0.000000  0.000000   
20  0.000000  0.000000    0.000000  0.430953  0.000000  0.000000  0.000000   

    acrylates  acrylatesc  acttackantiacne  ...  volcanic    vulgar     wajah  \
0    0.000000    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
1    0.083052    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
2    0.082372    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
3    0.085723    0.000000           0.1448  ...  0.000000  0.000000  0.000000   
4    0.082046    0.000000           0.0000  ...  0.138588  0.000000  0.000000   
5    0.073894    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
6    0.000000    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
7    0.083796    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
8    0.076457    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
9    0.000000    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
10   0.000000    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
11   0.000000    0.178966           0.0000  ...  0.000000  0.000000  0.203216   
12   0.000000    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
13   0.000000    0.151672           0.0000  ...  0.000000  0.000000  0.000000   
14   0.000000    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
15   0.000000    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
16   0.000000    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
17   0.000000    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
18   0.000000    0.000000           0.0000  ...  0.000000  0.000000  0.000000   
19   0.000000    0.000000           0.0000  ...  0.000000  0.215496  0.000000   
20   0.000000    0.000000           0.0000  ...  0.000000  0.000000  0.000000   

        wash     water       wax   wowtery   xanthan   xylitol       zea  
0   0.071955  0.052239  0.000000  0.000000  0.000000  0.000000  0.000000  
1   0.082574  0.179843  0.000000  0.000000  0.000000  0.000000  0.000000  
2   0.081897  0.059457  0.000000  0.139139  0.000000  0.000000  0.000000  
3   0.085229  0.061876  0.000000  0.000000  0.000000  0.000000  0.000000  
4   0.081573  0.059221  0.000000  0.000000  0.000000  0.000000  0.000000  
5   0.073467  0.053337  0.000000  0.000000  0.000000  0

In [44]:
pd.set_option("display.max_rows", 10)
asd = pd.DataFrame(df_tfidfvect)
asd

acetate    acetyl  acetylated      acid      acne    acocia  acrylate  \
0   0.09731  0.122248    0.000000  0.247512  0.000000  0.000000       0.0   
1   0.00000  0.000000    0.000000  0.094679  0.123548  0.140288       0.0   
2   0.00000  0.000000    0.101618  0.187807  0.000000  0.000000       0.0   
3   0.00000  0.000000    0.105752  0.244310  0.000000  0.000000       0.0   
4   0.00000  0.000000    0.101216  0.280595  0.000000  0.000000       0.0   
..      ...       ...         ...       ...       ...       ...       ...   
16  0.00000  0.000000    0.000000  0.075107  0.000000  0.000000       0.0   
17  0.00000  0.000000    0.000000  0.083212  0.000000  0.000000       0.0   
18  0.00000  0.000000    0.000000  0.093451  0.243889  0.000000       0.0   
19  0.00000  0.000000    0.000000  0.145436  0.000000  0.000000       0.0   
20  0.00000  0.000000    0.000000  0.430953  0.000000  0.000000       0.0   

    acrylates  acrylatesc  acttackantiacne  ...  volcanic    vulgar  wajah  \
0    0.000000         0.0           0.0000  ...  0.000000  0.000000    0.0   
1    0.083052         0.0           0.0000  ...  0.000000  0.000000    0.0   
2    0.082372         0.0           0.0000  ...  0.000000  0.000000    0.0   
3    0.085723         0.0           0.1448  ...  0.000000  0.000000    0.0   
4    0.082046         0.0           0.0000  ...  0.138588  0.000000    0.0   
..        ...         ...              ...  ...       ...       ...    ...   
16   0.000000         0.0           0.0000  ...  0.000000  0.000000    0.0   
17   0.000000         0.0           0.0000  ...  0.000000  0.000000    0.0   
18   0.000000         0.0           0.0000  ...  0.000000  0.000000    0.0   
19   0.000000         0.0           0.0000  ...  0.000000  0.215496    0.0   
20   0.000000         0.0           0.0000  ...  0.000000  0.000000    0.0   

        wash     water  wax   wowtery  xanthan   xylitol  zea  
0   0.071955  0.052239  0.0  0.000000      0.0  0.000000  0.0  
1   0.082574  0.179843  0.0  0.000000      0.0  0.000000  0.0  
2   0.081897  0.059457  0.0  0.139139      0.0  0.000000  0.0  
3   0.085229  0.061876  0.0  0.000000      0.0  0.000000  0.0  
4   0.081573  0.059221  0.0  0.000000      0.0  0.000000  0.0  
..       ...       ...  ...       ...      ...       ...  ...  
16  0.065504  0.000000  0.0  0.000000      0.0  0.000000  0.0  
17  0.072573  0.000000  0.0  0.000000      0.0  0.246595  0.0  
18  0.081502  0.000000  0.0  0.000000      0.0  0.000000  0.0  
19  0.063421  0.000000  0.0  0.000000      0.0  0.000000  0.0  
20  0.125284  0.000000  0.0  0.000000      0.0  0.000000  0.0  

[21 rows x 369 columns]

### Jika dilakukan pada seluruh data pengguna

In [45]:
#TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer

# import modul xlsxwriter untuk membantu menulis data ke excel
import xlsxwriter

# Membuat excel yang menjadi tujuan tuli
writer = pd.ExcelWriter('C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/HasilRekomendasiFix.xlsx', engine='xlsxwriter')
writer_two = pd.ExcelWriter(
    'C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/HasilTFIDF_FIX.xlsx', engine='xlsxwriter')
# Awal penulisan
row = 1
row_two = 1
col = 0
col_two = 0

data_index = pd.DataFrame({
  'index':[]
})

for i in range (0,len(data_pengguna)):
  print(data_pengguna['input'][i])

  #contoh inputan pengguna
  test_case = data_pengguna['input'][i]

  # melakuka text preprocessing pada inputan pengguna
  user_input = text_pre_input_two(test_case)
  # menambahkan ke dalam dataset
  add_data = pd.DataFrame({'data':user_input}, index=[-1])
  # print(add_data)

  # membuat variabel baru untuk menampung data product
  the_data = data_product

  #percabangan agar produk yang direkomendasikan sesuai dengan kategori
  if (test_case.find('Facial Wash')!=-1):
    # print ('Facial Wash')
    th_idx = pd.concat([dataset[0:20],add_data]).reset_index(drop=True)
    the_product = the_data[0:20]
  elif (test_case.find('Face Toner')!=-1):
    # print ('Face Toner')
    th_idx = pd.concat([dataset[20:40],add_data]).reset_index(drop=True)
    the_product = the_data[20:40]
  elif (test_case.find('Face Serum')!=-1):
    # print('Face Serum')
    th_idx = pd.concat([dataset[40:60],add_data]).reset_index(drop=True)
    the_product = the_data[40:60]
  elif (test_case.find('Moisturizer')!=-1):
    # print('Moisturizer')
    th_idx = pd.concat([dataset[60:80],add_data]).reset_index(drop=True)
    the_product = the_data[60:80]
  else :
    # print('Sunscreen')
    th_idx = pd.concat([dataset[80:100],add_data]).reset_index(drop=True)
    the_product = the_data[80:100]

  # TFIDF vectorizer
  vectorizer = TfidfVectorizer(analyzer='word', stop_words=list(data_stopword))
  # Mencari nilai TFIDF dari dataset yang telah ditentukan
  tfidf_dataset1 = vectorizer.fit_transform(th_idx['data'])
  # Mencari rekomendasi berdasarkan nilai cosine similarity yang didapatkan dari nilai TFIDF sebelumnya
  index, top5 = get_recommendations_product_two(tfidf_dataset1)

  df_tfidf_sklearn = pd.DataFrame(tfidf_dataset1.toarray(), columns=vectorizer.get_feature_names_out())
  tfidf_tokens = vectorizer.get_feature_names_out()
  df_tfidfvect = pd.DataFrame(data=tfidf_dataset1.toarray(), index=th_idx.index.values, columns=tfidf_tokens)

  df_tfidfvect.to_excel(writer_two, startrow=row_two)
  # Mengakses file excel dan sheet untuk menuliskan sesuatu
  work_book_tw = writer_two.book
  work_sheet_tw = writer_two.sheets["Sheet1"]
  row_two -= 1

  # Menuliskan 'test_case' pada baris dan kolom yang telah ditentukan
  work_sheet_tw.write(row_two, col_two, test_case)
  row_two += 23
  work_sheet_tw.write(row_two, col_two, str(df_tfidfvect.shape))
  row_two +=4

  # display(df_tfidfvect)
  # print(df_tfidfvect.shape)

  # Menyimpan hasil rekomendasi berdasarkan indexnya
  res_data = pd.DataFrame(the_product[['Nama', 'Jenis ']].iloc[index])
  # Menyamakan index antara hasil rekomendasi dengan hasil cosine similarity
  top5.index = res_data.index
  # Menggabungkan data 
  fix_res = pd.concat([res_data, top5], axis=1)
  # display(fix_res)

  index_two = set(fix_res.index.values)

  print(index_two)
  data_index_new = pd.DataFrame([{'index': index_two}])
  data_index = pd.concat([data_index, data_index_new], ignore_index=True)

  # Hasil rekomendasi dituliskan ke dalam excel
  fix_res.to_excel(writer, startrow=row)

  # Mengakses file excel dan sheet untuk menuliskan sesuatu
  work_book = writer.book
  work_sheet =  writer.sheets["Sheet1"]
  row-=1
  
  # Menuliskan 'test_case' pada baris dan kolom yang telah ditentukan
  work_sheet.write(row, col, test_case)
  row+= 10

# Menyimpan hasil yang telah dituliskan
writer.close()
writer_two.close()

Facial Wash Normal Normal  
{3, 6, 10, 11, 17}
Facial Wash Normal Kusam Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter 
{0, 3, 5, 8, 15}
Facial Wash Normal Jerawat Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil 
{1, 3, 4, 6, 15}
Facial Wash Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid 
{0, 3, 4, 5, 17}
Facial Wash Berminyak Kusam Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Shea Butter 
{0, 3, 4, 5, 17}
Facial Wash Berminyak Jerawat Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil 
{0, 3, 4, 5, 15}
Facial Wash Kering Normal Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea 
{3, 4, 6, 15, 17}
Facial Wash Kering Kusam Hyaluronic A

In [46]:
data_index['index'][11]

{3, 4, 5, 6, 15}

In [47]:
data_index.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/" +'IndexRekomendasi.xlsx', index=False)

# IMPORT DATA REKOMENDASI AHLI

In [48]:
pd.set_option('display.max_colwidth', 200)
# Membaca data csv
data_path = "C:\\Users\\HP\\Downloads\\TUGAS AKHIR\\Produk Skincare Data - Copy of Copy of data rekomendasi ahli.csv"
data_ahli = pd.read_csv(data_path)

# Menampilkan data
data_ahli.head(5)

NO Jenis Produk Jenis Kulit Permasalahan Kulit  Index  \
0   1  Facial wash      Normal             Normal     10   
1   1  Facial wash      Normal             Normal     11   
2   1  Facial wash      Normal             Normal     13   
3   1  Facial wash      Normal             Normal     14   
4   1  Facial wash      Normal             Normal     17   

                                 5 Rekomendasi  
0                       Kind Facial Wash 120ml  
1           Facial Wash Gel (Sabun Wajah) Rose  
2               Skin Barrier Face Gel Cleanser  
3  Deep Water Face & Light Makeup Gel Cleanser  
4                 Hydralife Mild Cleanser Foam

In [49]:
data_ahli.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   NO                  260 non-null    int64 
 1   Jenis Produk        260 non-null    object
 2   Jenis Kulit         260 non-null    object
 3   Permasalahan Kulit  260 non-null    object
 4   Index               260 non-null    int64 
 5   5 Rekomendasi       260 non-null    object
dtypes: int64(2), object(4)
memory usage: 12.3+ KB


In [50]:
data_ahli['Index'] = data_ahli['Index'].astype(object)

In [51]:
data_ahli = data_ahli.groupby('NO', as_index=False).agg(
    {'Jenis Produk': 'first', 'Jenis Kulit': 'first', 'Permasalahan Kulit': 'first', 'Index': lambda x: list(x), '5 Rekomendasi': ', '.join})

data_ahli.head(3)

NO Jenis Produk Jenis Kulit Permasalahan Kulit                 Index  \
0   1  Facial wash      Normal             Normal  [10, 11, 13, 14, 17]   
1   2  Facial wash      Normal              Kusam      [6, 14, 0, 1, 2]   
2   3  Facial wash      Normal            Jerawat    [18, 3, 8, 12, 15]   

                                                                                                                                                                                     5 Rekomendasi  
0                            Kind Facial Wash 120ml, Facial Wash Gel (Sabun Wajah) Rose, Skin Barrier Face Gel Cleanser, Deep Water Face & Light Makeup Gel Cleanser, Hydralife Mild Cleanser Foam  
1                Golden Age Deep Cleansing Facial Wash, Deep Water Face & Light Makeup Gel Cleanser, Marigold Deep-Cleanse Facial Wash, Acne Facial Wash, Hy! Amino Wow-tery Hydrating Facial Wash  
2  Acne Buster Mild Cleanser Foam, Hy! Amino Ac-TtackAnti-Acne Facial Wash, Simply Bright Facial Wash Grape & Hyaluronic Acid, Licorice Bring The Light Cleanser, Tea Tree & Lemon Facial Cleanser

In [52]:
data_ahli = data_ahli.drop(labels=["NO"], axis='columns')

In [54]:
data_ahli.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/" +'HasilRekomendasiAhli.xlsx', index=False)

# CONFUSION MATRIX

In [58]:
th_data_ahli = pd.read_excel(
    "C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/" + 'MatriksHasilRekomendasiAhli.xlsx')
th_data_ahli.head(3)

index
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1  [1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2  [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [59]:
th_data_sistem = pd.read_excel(
    "C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/" + 'MatriksHasilRekomendasiSistem.xlsx')
th_data_sistem.head(3)


index
0  [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1  [1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2  [0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [71]:
data_eval = pd.DataFrame({
  'Hasil Rekom Ahli' : [],
  'Hasil Rekom Sistem' : [],
  'True Positive (TP)' : [],
  'False Positive (FP)': [],
  'False Negative (FN)': [],
  'True Negative (TN)': [],
  'Accuracy' : [],
  'Precision' : [],
  'Recall' : [],
  'F1_Score' : []
})

In [72]:
import ast
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report

for i in range (0,len(th_data_ahli)):
  y_true = ast.literal_eval(th_data_ahli['index'][i])
  y_pred = ast.literal_eval(th_data_sistem['index'][i])

  # compute the confusion matrix
  conf_matrix = confusion_matrix(y_true, y_pred, labels=[1, 0])
  print("Confusion matrix:\n", conf_matrix)
  # print("TP :",conf_matrix[0][0])
  # print("FP :", conf_matrix[1][0])
  # print("FN :", conf_matrix[0][1])
  # print("TN :", conf_matrix[1][1])

  # compute other evaluation metrics
  accuracy = accuracy_score(y_true, y_pred)
  precision = precision_score(y_true, y_pred)
  recall = recall_score(y_true, y_pred)
  f1 = f1_score(y_true, y_pred)

  # print("Accuracy:", accuracy)
  # print("Precision:", precision)
  # print("Recall:", recall)
  # print("F1 Score:", f1)
  # print('\n')

  # print(classification_report(y_true, y_pred))

  data_eval_new = pd.DataFrame([{
      'Hasil Rekom Ahli': data_ahli['Index'][i],
      'Hasil Rekom Sistem': data_index['index'][i],
      'True Positive (TP)': conf_matrix[0][0],
      'False Positive (FP)': conf_matrix[1][0],
      'False Negative (FN)': conf_matrix[0][1],
      'True Negative (TN)': conf_matrix[1][1],
      'Accuracy': accuracy,
      'Precision': precision,
      'Recall': recall,
      'F1_Score': f1
  }])

  data_eval = pd.concat([data_eval, data_eval_new], ignore_index = True)


Confusion matrix:
 [[ 3  2]
 [ 2 93]]
Confusion matrix:
 [[ 1  4]
 [ 4 91]]
Confusion matrix:
 [[ 2  3]
 [ 3 92]]
Confusion matrix:
 [[ 1  4]
 [ 4 91]]
Confusion matrix:
 [[ 2  3]
 [ 3 92]]
Confusion matrix:
 [[ 2  3]
 [ 3 92]]
Confusion matrix:
 [[ 1  4]
 [ 4 91]]
Confusion matrix:
 [[ 1  4]
 [ 4 91]]
Confusion matrix:
 [[ 2  3]
 [ 3 92]]
Confusion matrix:
 [[ 2  3]
 [ 3 92]]
Confusion matrix:
 [[ 2  3]
 [ 3 92]]
Confusion matrix:
 [[ 3  2]
 [ 2 93]]
Confusion matrix:
 [[ 1  4]
 [ 4 91]]
Confusion matrix:
 [[ 2  3]
 [ 3 92]]
Confusion matrix:
 [[ 4  1]
 [ 1 94]]
Confusion matrix:
 [[ 2  3]
 [ 3 92]]
Confusion matrix:
 [[ 3  2]
 [ 2 93]]
Confusion matrix:
 [[ 3  2]
 [ 2 93]]
Confusion matrix:
 [[ 4  1]
 [ 1 94]]
Confusion matrix:
 [[ 3  2]
 [ 2 93]]
Confusion matrix:
 [[ 3  2]
 [ 2 93]]
Confusion matrix:
 [[ 3  2]
 [ 2 93]]
Confusion matrix:
 [[ 4  1]
 [ 1 94]]
Confusion matrix:
 [[ 3  2]
 [ 2 93]]
Confusion matrix:
 [[ 0  5]
 [ 5 90]]
Confusion matrix:
 [[ 3  2]
 [ 2 93]]
Confusion ma

In [73]:
data_eval

Hasil Rekom Ahli    Hasil Rekom Sistem  True Positive (TP)  \
0   [10, 11, 13, 14, 17]    {3, 6, 10, 11, 17}                 3.0   
1       [6, 14, 0, 1, 2]      {0, 3, 5, 8, 15}                 1.0   
2     [18, 3, 8, 12, 15]      {1, 3, 4, 6, 15}                 2.0   
3    [15, 16, 17, 19, 1]      {0, 3, 4, 5, 17}                 1.0   
4        [0, 1, 5, 7, 9]      {0, 3, 4, 5, 17}                 2.0   
..                   ...                   ...                 ...   
47  [70, 69, 79, 68, 72]  {69, 72, 75, 78, 79}                 3.0   
48  [90, 91, 82, 99, 92]  {96, 99, 86, 90, 93}                 2.0   
49  [80, 89, 82, 90, 84]  {96, 97, 86, 87, 92}                 0.0   
50  [90, 96, 86, 97, 88]  {96, 97, 99, 86, 93}                 3.0   
51  [90, 84, 87, 91, 89]  {96, 97, 99, 86, 93}                 0.0   

    False Positive (FP)  False Negative (FN)  True Negative (TN)  Accuracy  \
0                   2.0                  2.0                93.0      0.96   
1                   4.0                  4.0                91.0      0.92   
2                   3.0                  3.0                92.0      0.94   
3                   4.0                  4.0                91.0      0.92   
4                   3.0                  3.0                92.0      0.94   
..                  ...                  ...                 ...       ...   
47                  2.0                  2.0                93.0      0.96   
48                  3.0                  3.0                92.0      0.94   
49                  5.0                  5.0                90.0      0.90   
50                  2.0                  2.0                93.0      0.96   
51                  5.0                  5.0                90.0      0.90   

    Precision  Recall  F1_Score  
0         0.6     0.6       0.6  
1         0.2     0.2       0.2  
2         0.4     0.4       0.4  
3         0.2     0.2       0.2  
4         0.4     0.4       0.4  
..        ...     ...       ...  
47        0.6     0.6       0.6  
48        0.4     0.4       0.4  
49        0.0     0.0       0.0  
50        0.6     0.6       0.6  
51        0.0     0.0       0.0  

[52 rows x 10 columns]